CREATE DATABASE shopping;
USE shopping;

SELECT *FROM customers limit 20; 

-- Q1. List top 5 locations with the highest number of customers.

SELECT location, COUNT(customer_id) AS Customers_count FROM customers 
GROUP BY location
ORDER BY COUNT(customer_id)
LIMIT 5;

-- Q2. Which category has the highest total sales?

SELECT category, sum(purchase_amount) AS Total_revenue FROM customers
GROUP BY category
ORDER BY sum(purchase_amount) DESC
LIMIT 1;

-- Q3. Top 5 most purchased items.

SELECT item_purchased, COUNT(customer_id) Item_count FROM customers 
GROUP BY item_purchased
ORDER BY COUNT(customer_id) DESC
LIMIT 5;

-- Q4. What is the total revenue generated by male vs. female customers?

SELECT gender, sum(purchase_amount) AS Revenue FROM customers
GROUP BY gender;

-- Q5. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id, purchase_amount FROM customers 
WHERE discount_applied ="Yes" and purchase_amount > (SELECT avg(purchase_amount) FROM customers);

-- Q6. Top 3 categories sold in each season.
SELECT *FROM(
SELECT season, category ,COUNT(customer_id) AS Items_sold,
row_number() OVER(PARTITION BY season ORDER BY COUNT(customer_id) DESC) AS Rank_
FROM customers
GROUP BY category,season)T
WHERE Rank_<=3;

-- Q7. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, avg(review_rating) FROM customers
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5;

-- Q8. Which season has the highest average purchase amount?

SELECT AVG(purchase_amount) AS Total_revenue, season FROM customers
GROUP BY season
ORDER BY Total_revenue DESC
LIMIT 1;

-- Q9. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT shipping_type, round(avg(purchase_amount),2) FROM customers WHERE shipping_type IN ("Express", "Standard")
GROUP BY shipping_type;

-- Q10. Do subscribed customers generate more revenue than non-subscribed customers?

SELECT subscription_status, sum(purchase_amount) FROM customers 
GROUP BY subscription_status
ORDER BY sum(purchase_amount) DESC;


-- Q11. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, sum(purchase_amount) AS Total_Revenue ,
                            avg(purchase_amount) AS Average_spent , 
                            COUNT(customer_id) AS Number_ FROM customers 
GROUP BY subscription_status
ORDER BY Total_Revenue DESC;

-- Q12. Are discounts actually increasing revenue or just lowering prices?

SELECT discount_applied, COUNT(customer_id), SUM(purchase_amount), AVG(purchase_amount) FROM customers
GROUP BY discount_applied;

-- Q13. Does faster shipping improve customer satisfaction?

SELECT shipping_type,
       AVG(review_rating) AS avg_rating
FROM customers
GROUP BY shipping_type
ORDER BY avg_rating DESC;

-- Q14. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
SUM(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0 END)/COUNT(*) *100 AS Discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY Discount_rate DESC
LIMIT 5;


-- Q15. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE WHEN previous_purchases = 1 THEN "New"
     WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
     ELSE "Loyal"
     END AS Customer_segment
FROM customers     
)

SELECT Customer_segment, COUNT(*) AS Number_of_customers FROM customer_type 
GROUP BY Customer_segment; 

                                          -- -------------------------or ---------------------------
                                          
SELECT Customer_segment, COUNT(*) AS Number_of_customers FROM (SELECT customer_id, previous_purchases,
CASE WHEN previous_purchases = 1 THEN "New"
     WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
     ELSE "Loyal"
     END AS Customer_segment
FROM customers ) t
GROUP BY Customer_segment;   

-- Q16. What are the top 3 most purchased products within each category? 

WITH item_counts AS(
SELECT category, item_purchased,
COUNT(customer_id) AS Number_,
row_number() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rank_
FROM customers
GROUP BY category, item_purchased
) 

SELECT category, item_purchased, rank_, Number_ FROM item_counts WHERE rank_ <= 3;

-- ----------------------OR ------------------------

SELECT *FROM(
SELECT category, item_purchased,
COUNT(customer_id) AS Number_,
row_number() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rank_
FROM customers
GROUP BY category, item_purchased)T
WHERE rank_ <= 3; 

 
-- Q17. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status, count(customer_id) FROM customers 
WHERE previous_purchases > 5
GROUP BY subscription_status ;


-- Q18. What is the revenue contribution of each age group? 

SELECT age_group, SUM(purchase_amount) AS Total_revenue,
row_number() OVER(ORDER BY SUM(purchase_amount) DESC) AS rank_
FROM customers
GROUP BY age_group;

-- Q19. Identify top 10% customers by revenue.

SELECT *
FROM (
  SELECT customer_id,
         SUM(purchase_amount) AS total_spent,
         NTILE(10) OVER (ORDER BY SUM(purchase_amount) DESC) AS bucket
  FROM customers
  GROUP BY customer_id
) t
WHERE bucket = 1;

-- 20. Find customers who used discounts but gave low ratings (<3).

SELECT *
FROM customers
WHERE discount_applied  = 'Yes'
  AND review_rating < 3;

-- Q21. Detect locations with high revenue but low ratings.

SELECT location,
       SUM(purchase_amount) AS revenue,
       AVG(review_rating) AS avg_rating
FROM customers
GROUP BY location
HAVING avg_rating < 3.5
ORDER BY revenue DESC;